<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-10-28 18:01

$extensionPath = t3lib_extMgm::extPath('lowlevel_scheduler_task');
return array(
	'tx_lowlevelschedulertask_task_cleanup' => $extensionPath . 'task/class.tx_lowlevelschedulertask_task_cleanup.php',
	'tx_lowlevelschedulertask_task_cleanup_additionalfieldprovider' => $extensionPath . 'task/class.tx_lowlevelschedulertask_task_cleanup_AdditionalFieldProvider.php',
	'tx_lowlevelschedulertask_task_syslog' => $extensionPath . 'task/class.tx_lowlevelschedulertask_task_syslog.php',
	'tx_lowlevelschedulertask_task_syslog_additionalfieldprovider' => $extensionPath . 'task/class.tx_lowlevelschedulertask_task_syslog_AdditionalFieldProvider.php',
	'tx_lowlevelschedulertask_task_updaterefindex' => $extensionPath . 'task/class.tx_lowlevelschedulertask_task_updateRefindex.php',
	'tx_lowlevelschedulertask_task_updaterefindex_additionalfieldprovider' => $extensionPath . 'task/class.tx_lowlevelschedulertask_task_updateRefindex_AdditionalFieldProvider.php',
);
?>